ID-1131 Refactor GraphQLDispatcher
realifetech/ios-sdk pull request #54
Opened 2021-06-17 15:10 UTC by mickeylee25

Merge GraphNetwork and GraphQLDispatcher to `GraphQLManager`.

GraphQLManager fetches queries, perform mutations and clear cache via `client: ApolloClient`. The client is initialised in GraphQLFactory and the factory instantiates the GraphQLManager class from CoreFactory.

[BONUS]
- Fixed flaky test on DiskStorageTests
- Resolved TODO on AnalyticsLoggerTests by adding failure test cases

2021-06-18 07:37 UTC, You-Hsuan commented on Core/GraphQL/GraphQLManager.swift
>          mutation: Query,
How about we also change the generic parameter naming from `Query` to `Mutation` please? Thank you.

2021-06-18 09:06 UTC, thisolivier requested changes

2021-06-18 09:06 UTC, thisolivier commented on Core/CoreFactory.swift
>          reachabilityHelper: ReachabilityChecking
I notice this reachability helper isn't used any more, and never actually was. Please remove the argument here. 

- [ ] Remove reachabilityHelper

2021-06-18 09:25 UTC, mickeylee25 commented on Analytics/AnalyticsLogging/AnalyticsLogger.swift
> +    private func performPutAnalyticEventMutation(
Yes, we do need the repository/worker layer between GraphQLManager and interface implementation. I've created a [ticket](https://livestyled.atlassian.net/browse/ID-1134) for implementing this on Analytics, Audience and Content, so won't refactor them in this PR.

2021-06-18 09:29 UTC, mickeylee25 commented on Analytics/Tests/AnalyticsLoggingTests/AnalyticsLoggerTests.swift
> +                expectation.fulfill()
The test case does go to the success case but I should check if the boolean value is successful or not. I'll update the PR

2021-06-18 12:13 UTC, You-Hsuan approved these changes

2021-06-21 08:32 UTC, thisolivier approved these changes

2021-06-21 09:20 UTC, merged

2021-06-21 09:37 UTC, SoaringEarth commented on Analytics/Tests/AnalyticsLoggingTests/AnalyticsLoggerTests.swift
> +    func test_logEvent_onNotSuccess_delaySingleItem() {
could call this ...onFailure_delaySingleItem()